[package]
name = "sysinfo"
version = "0.1.0"
edition = "2024"

[dependencies]
sysinfo = "0.37"
serde.workspace = true
common.workspace = true
typetag.workspace = true
tracing.workspace = true
flume.workspace = true
eyre.workspace = true
tokio.workspace = true