[package]
name = "plot-common"
version = "0.1.0"
edition = "2024"

[dependencies]
macros.workspace = true
sensor-common.workspace = true
common.workspace = true
default-sensors.workspace = true
default-benches.workspace = true