[package]
name = "macros"
version = "0.1.0"
edition = "2024"

[dependencies]
convert_case = "0.8"
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"
serde.workspace = true
toml.workspace = true

[lib]
proc-macro = true
